apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: tesla
  name: list-nodes-binding
subjects:
  - kind: ServiceAccount
    name: my-sa
    namespace: tesla
roleRef:
  kind: Role
  name: list-nodes
  apiGroup: rbac.authorization.k8s.io
