version: '3.8'

services:
  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - "8093:8093"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3307/Mizdooni
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  frontend:
    build:
      context: ./Front/mizdooni
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Mizdooni
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
